services:
  openresty:
    image: openresty/openresty
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 3000:3000
      - 5000:5000
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis
