services:
  openresty:
    image: bitnami/openresty
    volumes:
      - './nginx.conf:/opt/bitnami/openresty/nginx/conf/server_blocks/nginx.conf:ro'
      - './index.lua:/opt/bitnami/openresty/nginx/conf/lua/index.lua:ro'
    ports:
      - '3000:3000'
      - '5000:5000'
      - '8000:8000'
  redis:
    image: redis
